alex/urls.py
from django.urls import path

from alex import views


urlpatterns = [
    path('create_card/', views.CardCreateView.as_view(), name='create-card'),
    path('list_cards/', views.CardListView.as_view(), name='list-cards'),
    path('create_deck/', views.DeckCreateView.as_view(), name='create-deck'),
    path('list_decks/', views.DeckListView.as_view(), name='list-decks'),
    path('details_deck/<int:pk>/', views.DeckDetailView.as_view(), name='details-deck'),
]

home/urls.py
from django.urls import path

from home import views

urlpatterns=[
    path('', views.HomeTemplateView.as_view(), name='homepage')
]

magic/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('alex.urls')),
    path('', include('home.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

alex/models.py
from django.contrib.auth.models import User
from django.db import models

from home.models import Player


# Create your models here.



class Deck(models.Model):

    name = models.CharField(max_length=50)
    commander = models.CharField(max_length=50)
    power_level = models.IntegerField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    profile = models.ImageField(upload_to='trainers/', null=True)
    players = models.ForeignKey(Player, on_delete=models.CASCADE, null=True)
    link =models.URLField(max_length=200, null=True)
    

    def __str__(self):
        return f'{self.name}'



class Card(models.Model):

    type_options = (
        ('creature','Creature'),
        ('instant','Instant'),
        ('sorcery', 'Sorcery'),
        ('artifact', 'Artifact'),
        ('enchantment', 'Enchantment'),
        ('battle', 'Battle'),
        ('planeswalker', 'Planeswalker'),

    )

    name = models.CharField(max_length=50)
    power = models.IntegerField(blank=True, null=True)
    toughness = models.IntegerField(blank=True, null=True)
    card_type = models.CharField(max_length=50, choices=type_options)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    deck = models.ForeignKey(Deck, on_delete=models.CASCADE, null=True)
    profile = models.ImageField(upload_to='cards/', null=True)
    points = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return f'{self.name}'

home/models.py
from django.contrib.auth.models import User
from django.db import models




class Player(models.Model):
    name = models.CharField(max_length=50)




    def __str__(self):
        return f'{self.name}'

alex/forms.py
from django import forms
from django.forms import TextInput, EmailInput, NumberInput, DateInput, Select
from alex.models import Deck, Card

class DeckForm(forms.ModelForm):
    class Meta:
        model = Deck

        fields = '__all__'

        widgets = {
            'name': TextInput(attrs={'placeholder': 'Please enter deck name', 'class': 'form-control'}),
            'commander': TextInput(attrs={'placeholder': 'Please the commanders name', 'class': 'form-control'}),
            'power_level': NumberInput(attrs={'placeholder': 'Please enter the power level of the deck', 'class': 'form-control'}),
            'players': Select(attrs={'class': 'form-select'}),

        }




class CardForm(forms.ModelForm):
    class Meta:
        model = Card
        # exclude = ['first_name']  -> il folosim pt a exclude anumite fielduri din formular / TREBUIE CA IN MODELS.PY SA AVETI BLANK= TRUE SI NULL=TRUE
        fields = '__all__'  # specificam fieldurile dorite in formular
        # fields = ['first_name', 'last_name']

        widgets = {
            'name': TextInput(attrs={'placeholder': 'Please enter the card name', 'class': 'form-control'}),
            'power': NumberInput(attrs={'placeholder': 'Please enter the card power', 'class': 'form-control'}),
            'toughness': NumberInput(attrs={'placeholder': 'Please enter the card toughness', 'class': 'form-control'}),
            'card_type': Select(attrs={'class': 'form-select'}),

            'points': NumberInput(attrs={'class': 'form-control', 'placeholder': 'Please enter the card points'}),
        }

    # Atunci cand creati sau personalizati un formular in Django puteti sa implementati validari personalizate
    # care se va aplica pe intregul formular

    # Aceasta metoda este folosita pentru a verifica corectitudinea datelor introduse de utilizator
    # inainte de fi procesate sau salve in baza de date

    def clean(self):
        cleaned_data = super().clean()  # se obtine access la informatiile din formular intr-un dictionar
        print(cleaned_data)

        return cleaned_data

alex/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.views.generic import CreateView, ListView, UpdateView, DetailView

from alex.filters import DeckFilter,CardFilter
from alex.forms import DeckForm, CardForm
from alex.models import Deck,  Card
from django.urls import reverse_lazy

class DeckCreateView(CreateView):
    template_name = 'deck/create_deck.html'  # randam un template dorit in care se va regasi formularul
    model = Deck  # modelului asociat formularului
    form_class = DeckForm
    success_url = reverse_lazy('homepage')


class DeckListView(ListView):
    template_name = 'deck/list_of_decks.html'
    model = Deck
    context_object_name = 'all_decks'

    def get_queryset(self):
        return Deck.objects.filter()

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)

        decks = Deck.objects.filter()
        myFilter = DeckFilter(self.request.GET, queryset=decks)
        decks = myFilter.qs
        data['all_decks'] = decks
        data['filters'] = myFilter.form
        return data



class DeckDetailView(DetailView):
    template_name = 'deck/details_deck.html'
    model = Deck

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cards'] = Card.objects.filter(deck=self.object)
        return context


class CardCreateView(CreateView):
    template_name = 'card/create_card.html' # randam un template dorit in care se va regasi formularul
    model = Card # modelului asociat formularului
    form_class = CardForm
    success_url = reverse_lazy('homepage')

    def form_valid(self, form):
        # Customizarea first_name si last_name pentru a le salva sub forma unui title()
        new_card = form.save(commit=False)
        new_card.name = new_card.name.title()
        new_card.save()




        return redirect('homepage')



class CardListView(ListView):
    template_name = 'card/list_of_cards.html'
    model = Card
    context_object_name = 'all_cards'


    def get_queryset(self):
        return Card.objects.filter()

    # Metoda get_context_data() este o metoda folosita in clase de view-uei (ListView, UpdateView, CreateView etc) pentru
    # a obtine si a pregati datele necesare pentru a fi afisate in template-ul ascociat.

    # Metoda este utilizata pentru a furnica contextul necesar pentru template pentru a afisa corect informatiile

    # Cand apelam get_context_data se obtine un dictionar de date pe care il trimitem in template, iar programatori pot
    # suplimenta cu informatii noi acel dictionar.
    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)

        cards = Card.objects.filter()
        myFilter = CardFilter(self.request.GET, queryset=cards)
        cards = myFilter.qs
        data['all_cards'] = cards
        data['filters'] = myFilter.form
        return data


def get_all_cards_per_deck(request, pk):
    card_per_deck = Card.objects.filter(deck_id=pk)

    return render(request, 'card/list_of_cards.html', {'all_cards': card_per_deck})

home/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


class HomeTemplateView(TemplateView):
    template_name = 'home/homepage.html' # specificam calea fisierului .html pe care o dorim randata/afisata.

templates/card/create_card.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Add Card</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="{% static 'img/favicon.ico' %}" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Nunito:wght@600;700;800&display=swap"
          rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body>
<!-- Spinner Start -->
<div id="spinner"
     class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
    <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
        <span class="sr-only">Loading...</span>
    </div>
</div>
<!-- Spinner End -->


<!-- Navbar Start -->
<nav class="navbar navbar-expand-lg bg-white navbar-light shadow sticky-top p-0">
    <a href="{% url 'homepage' %}" class="navbar-brand d-flex align-items-center px-4 px-lg-5">
        <h2 class="m-0 text-primary"><i class="fa fa-book me-3"></i>CommanderBoyz</h2>
    </a>
    <button type="button" class="navbar-toggler me-4" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <div class="navbar-nav ms-auto p-4 p-lg-0">
            <a href="{% url 'homepage' %}" class="nav-item nav-link active">Home</a>
            <div class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Cards</a>
                <div class="dropdown-menu fade-down m-0">
                    <a href="{% url 'create-card' %}" class="dropdown-item">Add Card</a>
                    <a href="{% url 'list-cards' %}" class="dropdown-item">List of cards</a>
                </div>
            </div>
            <div class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Decks</a>
                <div class="dropdown-menu fade-down m-0">
                    <a href="{% url 'create-deck' %}" class="dropdown-item">Add Deck</a>
                    <a href="{% url 'list-decks' %}" class="dropdown-item">List of decks</a>
                </div>
            </div>
        </div>
        <a href="" class="btn btn-primary py-4 px-lg-5 d-none d-lg-block">Play Now<i class="fa fa-arrow-right ms-3"></i></a>
    </div>
</nav>
<!-- Navbar End -->







 <div class="container-fluid">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <br><br>
                <div class="card">
                    <div class="card-header">
                        <h3 class="text-center">Add card</h3>
                    </div>
                    <form method="post" enctype="multipart/form-data">
                          {#                csrf_token securizeaza impotriva anumitor tipuri de atacuri, e un tag Django ce trebuie folosit in formulare:#}
                        {% csrf_token %}
                        <div class="card-body">

                               {#                form e variabila Django trimisa pe baza unui model(Student)#}
                            {{ form }}
                        </div>
                        <div class="card-footer text-center">
                            <button type="submit" class="btn btn-outline-success">Save</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>







<!-- Back to Top -->
<a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>


<!-- JavaScript Libraries -->
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
<script src="lib/wow/wow.min.js"></script>
<script src="lib/easing/easing.min.js"></script>
<script src="lib/waypoints/waypoints.min.js"></script>
<script src="lib/owlcarousel/owl.carousel.min.js"></script>

<!-- Template Javascript -->
<script src="{% static 'js/main.js' %}"></script>
</body>

</html>

templates/card/delete_card.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Delete Card</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="{% static 'img/favicon.ico' %}" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Nunito:wght@600;700;800&display=swap"
          rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body>
<!-- Spinner Start -->
<div id="spinner"
     class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
    <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
        <span class="sr-only">Loading...</span>
    </div>
</div>
<!-- Spinner End -->


<!-- Navbar Start -->
<nav class="navbar navbar-expand-lg bg-white navbar-light shadow sticky-top p-0">
    <a href="{% url 'homepage' %}" class="navbar-brand d-flex align-items-center px-4 px-lg-5">
        <h2 class="m-0 text-primary"><i class="fa fa-book me-3"></i>CommanderBoyz</h2>
    </a>
    <button type="button" class="navbar-toggler me-4" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <div class="navbar-nav ms-auto p-4 p-lg-0">
            <a href="{% url 'homepage' %}" class="nav-item nav-link active">Home</a>
            <div class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Cards</a>
                <div class="dropdown-menu fade-down m-0">
                    <a href="{% url 'create-card' %}" class="dropdown-item">Add Card</a>
                    <a href="{% url 'list-cards' %}" class="dropdown-item">List of cards</a>
                </div>
            </div>
            <div class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Decks</a>
                <div class="dropdown-menu fade-down m-0">
                    <a href="{% url 'create-deck' %}" class="dropdown-item">Add Deck</a>
                    <a href="{% url 'list-decks' %}" class="dropdown-item">List of decks</a>
                </div>
            </div>
        </div>
        <a href="" class="btn btn-primary py-4 px-lg-5 d-none d-lg-block">Play Now<i class="fa fa-arrow-right ms-3"></i></a>
    </div>
</nav>
<!-- Navbar End -->









<!-- Back to Top -->
<a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>


<!-- JavaScript Libraries -->
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
<script src="lib/wow/wow.min.js"></script>
<script src="lib/easing/easing.min.js"></script>
<script src="lib/waypoints/waypoints.min.js"></script>
<script src="lib/owlcarousel/owl.carousel.min.js"></script>

<!-- Template Javascript -->
<script src="{% static 'js/main.js' %}"></script>
</body>

</html>

templates/card/list_of_cards.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>List of Cards</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="{% static 'img/favicon.ico' %}" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Nunito:wght@600;700;800&display=swap"
          rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body>
<!-- Spinner Start -->
<div id="spinner"
     class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
    <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
        <span class="sr-only">Loading...</span>
    </div>
</div>
<!-- Spinner End -->


<!-- Navbar Start -->
<nav class="navbar navbar-expand-lg bg-white navbar-light shadow sticky-top p-0">
    <a href="{% url 'homepage' %}" class="navbar-brand d-flex align-items-center px-4 px-lg-5">
        <h2 class="m-0 text-primary"><i class="fa fa-book me-3"></i>CommanderBoyz</h2>
    </a>
    <button type="button" class="navbar-toggler me-4" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <div class="navbar-nav ms-auto p-4 p-lg-0">
            <a href="{% url 'homepage' %}" class="nav-item nav-link active">Home</a>
            <div class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Cards</a>
                <div class="dropdown-menu fade-down m-0">
                    <a href="{% url 'create-card' %}" class="dropdown-item">Add Card</a>
                    <a href="{% url 'list-cards' %}" class="dropdown-item">List of cards</a>
                </div>
            </div>
            <div class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Decks</a>
                <div class="dropdown-menu fade-down m-0">
                    <a href="{% url 'create-deck' %}" class="dropdown-item">Add Deck</a>
                    <a href="{% url 'list-decks' %}" class="dropdown-item">List of decks</a>
                </div>
            </div>
        </div>
        <a href="" class="btn btn-primary py-4 px-lg-5 d-none d-lg-block">Play Now<i class="fa fa-arrow-right ms-3"></i></a>
    </div>
</nav>
<!-- Navbar End -->








<div class="container-fluid">
        <div class="row">
            <div class="col-md-2">
                <div class='card'>
                    <div class='card-header'>
                        <h3 class="text-center">Filters</h3>
                    </div>
                    <form method="get">
                        <div class="card-body">
                            {{ filters }}
                        </div>
                        <div class="card-footer text-center">
                            <button type="submit" class="btn btn-outline-success">Search</button>
                            <a href="{% url 'list-cards' %}" class="btn btn-outline-danger">Reset</a>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-md-10">
                {% if all_cards %}

                    <table class="table">
                        <thead>
                        <tr>
                            <th>No.</th>
                            <th>Profile</th>
                            <th>Name</th>
                            <th>Power</th>
                            <th>Toughness</th>
                            <th>Card Type</th>
                            <th>Deck</th>
                            <th>Points</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for card in all_cards %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>
                                    {% if card.profile %}
                                        <img src="{{ card.profile.url }}"  width="40"
                                             height="60" alt="imagine profil">
                                    {% else %}
                                        <img src="{% static 'img/back2.jpg' %}" alt="imagine profil"
                                             width="60" height="60">
                                    {% endif %}
                                </td>
                                <td>{{ card.name }} </td>
                                <td>{{ card.power }}</td>
                                <td>{{ card.toughness }}</td>
                                {# lower, title, upper #}
                                <td>{{ card.card_type }}</td>
                                <td>{{ card.deck }}</td>
                                <td>{{ card.points|upper }}</td>



                            </tr>


                        {% endfor %}
                        </tbody>
                    </table>
                {% else %}
                    <div class="text-center">
                        No data available
                    </div>
                    "                               {% endif %}
            </div>
        </div>
    </div>










<!-- Back to Top -->
<a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>


<!-- JavaScript Libraries -->
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
<script src="lib/wow/wow.min.js"></script>
<script src="lib/easing/easing.min.js"></script>
<script src="lib/waypoints/waypoints.min.js"></script>
<script src="lib/owlcarousel/owl.carousel.min.js"></script>

<!-- Template Javascript -->
<script src="{% static 'js/main.js' %}"></script>
</body>

</html>

templates/deck/details_deck.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Deck Details</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="{% static 'img/favicon.ico' %}" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Nunito:wght@600;700;800&display=swap"
          rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>
<body>


<div class="card mb-3 ">
    <div class="row g-0">
        <div class="col-md-3 ">
            <img src="{{ deck.profile.url }}" class="img-fluid rounded-start" alt="...">
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <h4 class="card-title">Deck: {{ deck }}</h4>
                <h5 class="card-text">Commander: {{ deck.commander }}</h5>
                <h5 class="card-text">Power Level: {{ deck.power_level }}</h5>

                {% if deck.link %}
                    <a href="{{ deck.link }}" class="btn btn-success" target="_blank">Deck List</a>
                {% endif %}

 <a href="{% url 'list-decks' %}" class="btn btn-success" >Back to List of Decks</a>
            </div>
          
                
               

         
            {#                    {% for card in deck %}#}
            {#                        <img src="{{ card.profile.url }}" class="card-img-fluid" alt="imagine_profil"#}
            {#                                         >#}
            {#                        {% deck.card.profile.url %}#}
            {#                        #}
            {##}
            {#        {% endfor %}#}
            {#        #}

        </div>

    </div>
</div>



    

{##}
{#cards in deck #}
{##}
<div class="row">
<h2>Cards in deck:</h2>
    {% for card in cards %}
        <div class="col-md-2 mb-3">
            <div class="card">
                <img src="{{ card.profile.url }}" class="card-img-fluid height=" 250" width="150" alt="{{ card.name }}">
                <div class="card-body">
                    <h5 class="card-title">{{ card.name }}</h5>
                    <p class="card-text">Type: {{ card.get_card_type_display }}</p>
                    {% if card.power and card.toughness %}
                        <p class="card-text">Power/Toughness: {{ card.power }}/{{ card.toughness }}</p>
                    {% endif %}
                    <p class="card-text">Points: {{ card.points }}</p>
                </div>
            </div>
        </div>
    {% endfor %}
</div>


</body>
</html>